local gt = this.getroottable();
gt.Const.CharacterSprites <- {
	Armor = [
		"armor",
		"armor_layer_chain",
		"armor_layer_plate",
		"armor_layer_tabbard",
		"armor_layer_cloak_front",
		"armor_layer_cloak",
		"armor_upgrade_back",
		"armor_upgrade_front",
		"helmet_vanity_lower",
		"helmet_vanity_lower_2",
		"helmet",
		"helmet_damage",
		"helmet_helm",
		"helmet_top",
		"helmet_vanity",
		"helmet_vanity_2",
		"shield_icon"
	],
	Helmets = [
		"helmet_vanity_lower",
		"helmet_vanity_lower_2",
		"helmet",
		"helmet_damage",
		"helmet_helm",
		"helmet_top",
		"helmet_vanity",
		"helmet_vanity_2"
	],
	Human = [
		"arms_icon",
		"socket",
		"body",
		"tattoo_body",
		"scar_body",
		"surcoat",
		"bandage_2",
		"bandage_3",
		"shaft",
		"head",
		"eye_rings",
		"tattoo_head",
		"scar_head",
		"injury",
		"permanent_injury_3",
		"permanent_injury_2",
		"permanent_injury_scarred",
		"permanent_injury_burned",
		"beard",
		"hair",
		"permanent_injury_4",
		"permanent_injury_1",
		"accessory",
		"accessory_special",
		"beard_top",
		"bandage_1",
		"body_blood",
		"dirt"
	]
};

