local gt = this.getroottable();
gt.Const.TipOfTheDay <- [
	"As brothers we fight, as brothers we die!",
	"The arenas in the south do not sate the expectations of some - for that there is another place far, far away from prying eyes...",
	"If you are having trouble killing trees, try bringing axes.",
	"You don\'t have to be a hero, you\'re running a business.",
	"Success in Battle Brothers is also about picking the right fights.",
	"It is said there are wise women in the north who can commune with spirits and carve rune stones",
	"If you don\'t get hit, you can\'t be killed. Simple.",
	"Expect to lose some mercenaries.",
	"Losing is fun.",
	"Dying is part of a mercenary\'s job description.",
	"Forests can hide many dangers within.",
	"Not every battle can be won.",
	"A life can be worth little in this world.",
	"Wiedergangers are the dead walking again.",
	"Geists are lost between the physical world and the world beyond, constantly shifting between the two.",
	"Some people will use you and throw you away.",
	"If your plan can fail with bad luck, maybe it isn\'t good enough of a plan.",
	"Learn from your mistakes. Don\'t just repeat them and hope you\'ll get lucky this time.",
	"Do the job. Survive. Get paid.",
	"Shields can be destroyed using axes and some two-handed weapons.",
	"Different types of shields can be better suited against melee or ranged attacks.",
	"Bucklers and parry daggers are exceptional against small groups or single targets.",
	"Alt click on friendly caravans to attack them.",
	"Shields take minor damage each time they are used to deflect an attack, shield expert reduces this damage significantly.",
	"Shrubbery can hide characters from being detected from afar.",
	"A character with a height level advantage over their opponent is harder to hit.",
	"Characters can see farther, the higher they are positioned.",
	"Surrounding an opponent from multiple sides makes it easier to score a hit.",
	"Consider putting injured characters in reserve until their wounds have healed.",
	"Consider building up a reserve roster and rotating your mercenaries, so you can more easily deal with losses down the road.",
	"A missed ranged attack can hit nearby characters, especially if they are in the direct line of fire.",
	"Economic difficulty impacts recruit frequency. A more difficult economy will yield fewer recruits.",
	"Ranged weapons work best when firing into groups of enemies - they are bound to hit someone.",
	"Consider forming a shieldwall when overwhelmed.",
	"Fulfilling ambitions will raise everyone\'s mood and grant you renown, as well as some unique rewards.",
	"Use \'CTRL\' + \'Left Click\' to attack allied parties on the worldmap. This only works if you are currently unemployed.",
	"Stunned characters get no attack of opportunity when someone moves inside their zone of control.",
	"Try playing a campaign in legendary mode once you\'ve gained some experience - it\'s the recommended difficulty.",
	"The minimum hit chance for any attack is 5%, and the maximum hit chance for any attack is 95%.",
	"Characters may sometimes be struck down during combat, but not outright killed, and will survive with a permanent injury.",
	"If an opponent has better ranged skills than you, try attacking at night.",
	"Forests, swamps, and mountains can be used to create choke points to defend against greater numbers.",
	"If your company can run faster than an enemy, eventually they will stop chasing you.",
	"Conserve your stamina when in prolonged engagements.",
	"There is a button next to each character profile to put them into reserve.",
	"The Black Market contains items otherwise hard to find - for the right price.",
	"Hunting beasts can get you powerful runes to upgrade your gear",
	"Getting hit or dodging exhausts you. The same goes for most of your enemies",
	"You can instantly repair items for crowns at armorsmiths",
	"Find the right terrain for your party - flat fields do not always make the best battlefields.",
	"You can change camera height levels using the + and - keys.",
	"Try to save some crowns for when things turn sour.",
	"You can zoom in and out using the mouse wheel or Page Up and Page Down keys.",
	"All legendary beasts have weaknesses.",
	"Try the Ironman mode to experience Battle Brothers the way it\'s meant to be played.",
	"Ranged weapons are less accurate at night - those of your enemies included.",
	"Some parts of the world are more dangerous than others.",
	"Use ports to fast travel around the world.",
	"Use terrain and chokepoints to your advantage.",
	"The higher their level, the more your men will demand in wages.",
	"View range is decreased at night, both in combat and on the worldmap.",
	"Heavy armor offers great protection, but also slows down the wearer and makes them tire more quickly.",
	"Heavy helmets can be hard to breathe in and limit the field of vision.",
	"You can change gamespeed in the gameplay tab of the \'Options\' menu!",
	"Different types of enemies require different tactics to beat reliably.",
	"Every enemy in the can be beaten reliably with the right approach.",
	"A human is no match for an adult orc physically.",
	"Orc Berserkers gain rage and get tougher to take down, the more blood they have drawn.",
	"Geists test the resolve of your mercenaries - the lower, the more likely they are to panic and flee.",
	"Orcs rely on raw power and physical prowess.",
	"A goblin is no match for an adult human physically, so they rely on wit and dirty tricks.",
	"Always keep a good stock of provisions - lest your company starve and desert you!",
	"Difficult terrain, such as mountains and swamp, has your mercenaries use more supplies on the worldmap.",
	"If you can not win, retreat to fight another day.",
	"Try to reach the very edges of the map before retreating, or you\'ll risk your company sustaining serious injuries.",
	"Retreat. Flee. Don\'t fight every battle to the death.",
	"Use the \'spacebar\' key to pause on the worldmap.",
	"The natural habitat of direwolves is the forest.",
	"You can enable \'Faster AI turns\' in the \'Options\' menu.",
	"Trees can be hidden in combat using the \'T\' key.",
	"Objects blocking tiles can be highlighted using the \'B\' key.",
	"Higher renown will unlock more difficult contracts and better pay.",
	"You need a minimum of 10% bonus across all your brothers for a favoured enemy perk to spawn champions or legendary beasts more frequently",
	"You can change the styles of items in the painting tent, located in your camp. For a price, of course.",
	"Tower shields are cumbersome, but can be used to protect others in addition to the user.",
	"If a character waits their turn, their position in the turn order of the next round is determined with a penalty of 25% to Initiative.",
	"A 95% chance to hit is also a 5% chance to miss.",
	"Glaives, while still spears, do not benefit from thrust master.",
	"With staff block, swordstaffs gain 50% of the bonus.",
	"Just because a brother can\'t deal damage, doesn\'t mean they can\'t be useful.",
	"There are things more sinister in the sands than the old empire...",
	"Consider that enemy encampments on hills are harder to assault, especially if they are fortified.",
	"In the Inventory/Character Screen page, \'A\' key selects previous brother, \'D\' key selects next brother, the \'S\' key toggles reserve status.",
	"At 15 points of intensive training will reward that brother with a free perk point and trait",
	"Larger groups on the world map move more slowly - regardless of terrain.",
	"The \'Intensive Training\' trait can be increased by spending time training with that brother",
	"Increase your roster size by gaining renown!",
	"If you keep losing to an enemy, change your tactics!",
	"The larger a party on the worldmap, the slower it moves. Yours included.",
	"Use wardogs to hunt down elusive or fleeing enemies.",
	"Use a trained falcon to discover hidden enemies on difficult terrain.",
	"Keep an eye on the mood of your mercenaries. If they are angry for too long, they may desert!",
	"Elevated terrain like hills and mountains allow you to see farther on the worldmap.",
	"You can have your items repaired at the smith for a fee by using \'ALT\' + \'Right Click\'.",
	"You may find powerful named items far away from civilization by exploring or following tavern rumors.",
	"Food can be equipped and consumed in battle to restore health and fatigue.",
	"Ancient Scrolls can have random powerful effects when read. They can be identified by scholars.",
	"Ranged weapon accuracy drops with distance, unless you are using a northern slingstaff.",
	"Slings have unlimited ammo, but still break from use.",
	"Bows perform better against unarmored targets.",
	"Daggers can be used to attack weak spots in armor and deal damage directly to hitpoints.",
	"Wooden stakes do extra damage against necrosavants.",
	"Crossbows require less skill to fire accurately than bows, but are slower to use.",
	"Clubs and maces can stun or incapacitate targets.",
	"Throwing weapons can be deadly on short distances, but their accuracy drops sharply the farther away the target is.",
	"Longswords are more agile then Zweihanders or Greatswords - bigger is not always better!",
	"Spears are good defensive weapons due to their Spearwall ability.",
	"Spears and Swords are ideal for new recruits due to their simplicity.",
	"Estocs are strong fencing swords, but require two hands to use.",
	"Consider using Warbrands or Longswords to better benefit from \'Double Strike\' or \'Reach Advantage\' perks.",
	"Use throwing nets to restrict the movement of particularly dangerous enemies.",
	"Warhammers and Military Picks can make short work of heavy armor.",
	"The Billhook, Pike and Longaxe can attack over 2 tiles, unlike most other melee weapons.",
	"Flails ignore the defense bonus of shields.",
	"Two-handed axes can hit both head and body with a single hit.",
	"Two-handed axes can hit up to 6 targets with a single round swing.",
	"Cleavers can inflict bleeding wounds.",
	"Staffs and slings are ideal supporting weapons for characters who are not fit for direct combat.",
	"Have you assigned all your characters to camp tasks recently?",
	"Training in camp will give you raw experience points - the longer you train the bigger the rewards and the risks.",
	"You can toggle repair twice in your inventory to set items to scrap.",
	"Herbalists can gather medicine, poisons and mushrooms when assigned to gather in camp.",
	"Make camp to have your company heal and repair their equipment faster.",
	"Use \'ALT\' + \'Right Click\' to mark items for repair in your stash. Items equipped by your mercenaries are repaired automatically.",
	"Training in camp may result in a temporary injury without the training tent upgrade - but training with a temporary injury could cause a permanent one!",
	"The \'Scholar\' perk can allow characters to increase the amount of loot they find after battle.",
	"Unarmed is good at tiring out enemies who have roughly similar or lower total stamina than you, and puts them at a disadvantage.",
	"Perks are not exclusive to the group they came with.",
	"Those with the \'Potion Brewer\' perk can craft potions while gathering, including potions of knowledge.",
	"The \'Steel Brow\' perk can turn round-ending stuns into mere dazes.",
	"The \'Perfect Focus\' perk is a good way to deal a lot of damage quickly, for a price.",
	"The \'Nimble\' perk only protects hitpoints, not armour.",
	"The \'Ballistics\' skill can greatly increase your chance to hit at far ranges",
	"Learn the \'Rotation\' or \'Footwork\' perks for additional mobility in battle.",
	"The \'Lone Wolf\' perk is not affected by nearby dogs or allies that are not part of your company.",
	"The \'Fast Adaptation\' perk reduces variance of randomness.",
	"A character dedicated to unarmed combat may lack damage, but they make up for it with utility.",
	"Grappling an enemy sets them up to be choked and deal a large amount of damage.",
	"Jugglers can leap and tumble, and have a great aim.",
	"Herbalists can create items and brew potions.",
	"Peddlers trade bonuses stack, trade runs are possible.",
	"The Cabal uses medicine to keep their minions ready to summon.",
	"Valas are mystic women capable of inscribing powerful runes on your gear.",
	"Hiring different backgrounds affects your healing rate, repair, trade, food and movement speed. Try a varied roster.",
	"Apprentices, blacksmiths and ironmongers can help repair your equipment quickly.",
	"Your stash and resource size is determined by the people you hire.",
	"Women have more fatigue but less health than their male counterparts.",
	"Hunters and poachers will help you move through forests more quickly.",
	"Bakers and Servants can craft food into fresh pies and puddings.",
	"Houndmasters can improve the combat skills of dogs and breed them.",
	"Fishermen and Ratcatchers can develop powerful net skills.",
	"Inventors can craft prosthetics to help permanent injuries be less of a burden.",
	"Minstrels can play powerful music to heal, restore and control the battlefield.",
	"Cultists have strong resolve and skills in the right conditions.",
	"Eunuchs are immune to the charms of hexen.",
	"Avatars cannot be charmed.",
	"Highly talented characters can come from all backgrounds.",
	"Farmhands are skilled with a variety of farm tools.",
	"Hiring cannibals can keep you well fed after battles with humans.",
	"Taxidermists are experts at crafting in camp.",
	"Tailors and seamstresses can unlock cloak crafting.",
	"Warlocks require medicine to maintain their thralls, but food to occupy their puppets.",
	"Miners help you move quickly through mountains.",
	"Indebted, Wildmen and Brawlers have the potential to become skilled unarmed combatants.",
	"A Blacksmith can repair armour in battle...for a steep cost.",
	"Herbalists and Monks can heal in battle...for a steep cost.",
	"Your mercenaries will interact with each other differently depending on their backgrounds and traits.",
	"Unholds and Rock Unhold regeneration can be countered with spider poison.",
	"Defeating a Schrat may reward you with an enchanted shield rune.",
	"Defeating Hexe may reward you with an enchanted helm rune.",
	"Defeating a Demon Alp will reward you with a weapon rune of unbreaking.",
	"The Undead are unaffected by fatigue and morale.",
	"Alps, Schrats and Hexen can drop powerful runes to upgrade your gear.",
	"Spiders can ignore armor completely if their target is webbed.",
	"Wiederganger\'s bite can infect the target, and being killed by it can even cause it to be risen to fight on their side.",
	"Skeletons are highly resistant to ranged attacks and fire. But less so to throwing axes and crossbows.",
	"Every seven days settlements will increase in wealth naturally.",
	"Successful contracts and trade caravans will increase a settlement\'s wealth.",
	"Raiding will decrease a settlement\'s wealth over time, if it falls below 50%, it may decrease in size.",
	"Greenskins and Undead can permamently destroy settlements, keep an eye on the frontier!",
	"Selling in rich and big cities will net you the most crowns for your goods.",
	"Use trading to supplement your income.",
	"When a settlement\'s wealth is above 100%, it has a chance to grow and upgrade. Take care of your settlements...or don\'t.",
	"Roads are the fastest way to travel over land, but not always the safest.",
	"Many threats are drawn to roads and will lie in ambush for any who come near.",
	"Not every contract is worth the risk.",
	"Try to negotiate better payment for your contracts.",
	"Try to negotiate payment modalities that guarantee you the most money for contracts.",
	"Betraying your employer can have repercussions in the long run.",
	"Breaking a contract will anger your employer - especially if you\'ve received advance payment.",
	"Fortifications will only offer you contracts from the noble house that owns them.",
	"Nobles give contracts only to mercenary companies with professional renown.",
	"If contract negotiations turn sour, it will damage your relations with your potential employer.",
	"You can find contract offers in the top left of settlement screens."
];
gt.Const.LoadingScreens <- [
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_02.jpg",
	"ui/screens/loading_screen_03.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_07.jpg",
	"ui/screens/loading_screen_08.jpg"
];

