local gt = this.getroottable();
gt.Const.TipOfTheDay <- [
	"As brothers we fight, as brothers we die!",
	"The arenas in the south do not sate the expectations of some - for that there is another place far, far away from prying eyes",
	"Cooking recipes can heal and create a tidy profit",
	"The \'scholar\' perk can allow brothers to increase the amount of loot they find after battle.",
	"Ancient Scrolls can have random powerful effects when read. They can be identified by scholars.",
	"Jugglers can leap and tumble, and have a great aim.",
	"Herbalists can create herbal cures for fun and profit",
	"Shields can be destroyed using axes and some two-handed weapons.",
	"If you are having trouble killing trees, try bringing axes.",
	"Different types of shields are better suited against melee or ranged attacks.",
	"Bucklers and parry daggers are exceptional against small groups or single targets.",
	"Peddlers trade bonuses stack, trade runs are possible",
	"The Warlock uses medicine to keep his minions ready to summon",
	"Alt click on friendly caravans to attack them",
	"Shields take minor damage each time they are used to deflect an attack, shield expert reduces this damage significantly.",
	"Shrubbery can hide characters from being detected from afar.",
	"A character with a height level advantage over their opponent is harder to hit.",
	"Characters can see farther, the higher they are positioned.",
	"Hiring different backgrounds affects your heal, repair, trade, food and movement",
	"Surrounding an opponent from multiple sides makes it easier to score a hit.",
	"Consider putting injured characters in reserve until their wounds have healed.",
	"Have you assigned all your brothers to camp tasks recently?",
	"Training in camp will give you raw experience points - the longer you train the bigger the rewards.",
	"Consider building up a reserve roster and rotating your mercenaries, so you can more easily deal with losses down the road.",
	"Ranged weapon accuracy drops with distance, unless you are using a slingstaff.",
	"Female professions have more fatigue but less health than their male counterparts",
	"Your stash and resource size is determined by the people you hire",
	"Apprentices, blacksmiths and ironmongers can help repair your equipment quickly",
	"Magic missile damage is based on your initiative, but the accuracy is based on ranged attack.",
	"You don\'t have to be a hero, you\'re running a business.",
	"Valas are mystic women capable of inscribing powerful runes on your gear.",
	"A missed ranged attack can hit nearby characters, especially if they are in the direct line of fire.",
	"Slings have unlimited ammo, but still break from use",
	"Bows perform better against unarmored targets.",
	"Economic difficulty impacts recruit frequency.",
	"Daggers can be used to attack weak spots in armor and deal damage directly to hitpoints.",
	"Unarmed melee attack damage is based on your current hitpoints and initiative. Be suspicious of disarmed Orcs",
	"Ranged weapons work best when firing into groups of enemies - they are bound to hit someone.",
	"Unholds and Rock unhold regeneration can be stopped with spider poison",
	"Consider forming a shieldwall when overwhelmed.",
	"If an opponent has better ranged skills than you, try attacking at night",
	"Forests, swamps, and mountains can be used to create choke points to defend against greater numbers",
	"If your company can run faster than an enemy, eventually they will stop chasing you.",
	"Defeating a schrat may reward you with an enchanted shield rune",
	"Defeating hexen may reward you with an enchanted helm rune",
	"Defeating a demon alp will reward you with a weapon rune of unbreaking",
	"Wooden stakes do extra damage against necrosavants",
	"Perks are not exclusive to the group they came with.",
	"Conserve your stamina when in prolonged engagements.",
	"Success in Battle Brothers is also about picking the right fights.",
	"Undead are unaffected by fatigue and morale.",
	"Crossbows require less skill to fire accurately than bows, but are slower to use.",
	"Hunters and poachers will help you move through forests quicker",
	"There is a button next to each character profile to put them into reserve",
	"Alps, schrats and hexen can drop powerful runes to upgrade your gear",
	"Hunting beasts can get you powerful runes to upgrade your gear",
	"You can toggle repair twice in your inventory to set items to scrap",
	"Getting hit or dodging exhausts you. The same goes for most of your enemies",
	"Spiders can ignore your armor completely if you are webbed",
	"Wiederganger\'s bite can infect the target, and being killed by it can even cause it to be risen to fight on their side",
	"You can instantly repair items for coins at armorsmiths",
	"Herbalists can gather medicine, poisons and mushrooms when assigned to gather in camp",
	"Those with the \'Potion Brewer\' perk can craft potions while gathering, including potions of knowledge.",
	"Bakers and servants can craft rotten food into fresh pies and puddings",
	"You can equip food and eat it in battle to restore health",
	"It is said there are wise women in the north who can commune with spirits and carve rune stones",
	"Houndmasters can improve and breed dogs",
	"Retinue members can be hired by recruiting brothers with specfic perks unlocked.",
	"Fishermen can develop powerful net skills.",
	"Inventors can craft prosthetics to help permanent injuries",
	"Minstrels can play powerful music to heal, restore and control the battlefield",
	"Cultists have skills around resolve and causing bleeding",
	"Eunuchs are immune to the charms of hexen",
	"Avatars cannot be charmed",
	"If you don\'t get hit, you can\'t be killed. Simple.",
	"Farmhands are skilled with a variety of farm tools.",
	"Hiring cannibals can keep you well fed after battles with humans.",
	"Taxidermists are experts at crafting in camp.",
	"Tailors and seamstresses can unlock cloak crafting.",
	"Warlocks require medicine to maintain their thralls.",
	"Hunting beasts can get you powerful runes to upgrade your gear.",
	"Some difficult terrain, like swamps, give combat penalties.",
	"You can change camera height levels using the + and - keys.",
	"Clubs and maces can stun or incapacitate targets.",
	"Miners help you move quickly through mountains, a few miners in your squad lets you quick march through hills",
	"Try to save some crowns for when things turn sour.",
	"Longswords and Greatswords can hit multiple targets with one strike.",
	"You can zoom in and out using the mouse wheel or Page Up and Page Down keys.",
	"Spears are good defensive weapons due to their Spearwall ability.",
	"Expect to lose some mercenaries.",
	"Estocs are versatile two handed swords, but are quite fragile in comparison.",
	"Consider using warbrands or longswords to better benefit from double strike or reach advantage.",
	"All legendary beasts have weaknesses. Except Stollwurms. Stollwurms don\'t care.",
	"Losing is fun.",
	"A blacksmith can repair armour in battle...for a steep cost.",
	"Herbalists and monks can heal in battle...for a steep cost.",
	"Use terrain and chokepoints to your advantage.",
	"The higher their level, the more your men will demand in wages.",
	"Selling in rich and big cities will net you the most crowns for your goods.",
	"Use throwing nets to restrict the movement of particularly dangerous enemies.",
	"Use trading to supplement your income.",
	"When a settlement\'s wealth is above 100%, it has a chance to grow and upgrade. Take care of your settlements...or don\'t.",
	"Every seven days settlements will increase in wealth naturally.",
	"Successful contracts and trade caravans will increase a settlement\'s wealth.",
	"Raiding will decrease a settlement\'s wealth over time, if it falls below 50%, it may decrease in size.",
	"Greenskins and undead can permamently destroy settlements if their level drops to zero, keep an eye on the frontier!",
	"Learn the \'Rotation\' or \'Footwork\' perks for additional mobility in battle.",
	"View range is decreased at night, both in combat and on the worldmap.",
	"Skeletons are highly resistant to ranged attacks and fire.",
	"Heavy armor offers great protection, but also slows down the wearer and makes him tire more quickly.",
	"Heavy helmets can be hard to breathe in and limit the field of vision.",
	"You can change gamespeed in the gameplay tab of options!",
	"Warhammers and Military Picks can make short work of heavy armor.",
	"The Billhook, Pike and Longaxe can attack over 2 tiles, unlike most other melee weapons.",
	"Flails ignore the defense bonus of shields.",
	"Different types of enemies require different tactics to beat reliably.",
	"Every enemy in the game can be beat reliably with the right approach.",
	"A human is no match for an adult orc physically.",
	"Orcs rely on raw power and physical prowess.",
	"A goblin is no match for an adult human physically, so they rely on wit and dirty tricks.",
	"Orc Berserkers gain rage and get tougher to take down, the more blood they have drawn.",
	"Geists are lost between the physical world and the world beyond, constantly shifting between the two.",
	"Geists test the resolve of your mercenaries - the lower, the more likely they are to panic and flee.",
	"Two-handed axes can hit both head and body with a single hit.",
	"Two-handed axes can hit up to 6 targets with a single round swing.",
	"Roads are the fastest way to travel over land, but not always the safest.",
	"Forests can hide many dangers within.",
	"Always keep a good stock of provisions - lest your company starve and desert you!",
	"Wiedergangers are the dead walking again.",
	"Difficult terrain, such as mountains and swamp, has your mercenaries use more supplies on the worldmap.",
	"If you can not win, retreat to fight another day.",
	"Try to reach the very edges of the map before retreating, or you\'ll risk your company sustaining serious injuries.",
	"Retreat. Flee. Don\'t fight every battle to the death.",
	"Use the spacebar key to pause on the worldmap.",
	"Elevated terrain like hills and mountains allow you to see farther on the worldmap.",
	"Not every contract is worth the risk.",
	"Try to negotiate better payment for your contracts.",
	"Try to negotiate payment modalities that guarantee you the most money for contracts.",
	"Not every battle can be won.",
	"A life can be worth little in this world.",
	"Betraying your employer can have repercussions in the long run.",
	"Some parts of the world are more dangerous than others.",
	"Use ports to fast travel around the world.",
	"Some people will use you and throw you away.",
	"Throwing weapons can be deadly on short distances, but their accuracy drops sharply the farther away the target.",
	"Highly talented characters can come from all backgrounds.",
	"Try the Ironman mode to experience Battle Brothers the way it\'s meant to be played.",
	"Ranged weapons are less accurate at night - those of your enemies included.",
	"Make camp to have your company heal and repair their equipment faster.",
	"Use ALT + Right Click to mark items for repair in your stash. Items equipped by your mercenaries are repaired automatically.",
	"You can have your items repaired at the smith for a fee by using ALT + Right Click.",
	"Breaking a contract will anger your employer - especially if you\'ve received advance payment.",
	"Fortifications will only offer you contracts from the noble house that owns them.",
	"Nobles give contracts only to mercenary companies with professional renown.",
	"If contract negotiations turn sour, it will damage your relations with your potential employer.",
	"You can find contract offers in the top left of settlement screens.",
	"You may find powerful named items far away from civilization by exploring or following tavern rumors.",
	"Dying is part of a mercenary\'s job description.",
	"Keep an eye on the mood of your mercenaries. If they are angry for too long, they may desert!",
	"If you keep losing to an enemy, change your tactics!",
	"The larger a party on the worldmap, the slower it moves. Yours included.",
	"Use wardogs to hunt down elusive or fleeing enemies.",
	"Use a trained falcon to discover hidden enemies on difficult terrain.",
	"Cleavers can inflict bleeding wounds.",
	"Fulfilling ambitions will raise everyone\'s mood and grant you renown, as well as some unique rewards.",
	"Use CTRL + Left Click to attack allied parties on the worldmap. This only works if you are currently unemployed.",
	"Your mercenaries will interact with each other differently depending on their backgrounds and traits.",
	"Stunned characters get no attack of opportunity when someone moves inside their zone of control.",
	"Try playing a campaign in legendary mode once you\'ve gained some experience - it\'s the recommended difficulty.",
	"The minimum hit chance for any attack is 5%, and the maximum hit chance for any attack is 95%.",
	"Characters may sometimes be struck down during combat, but not outright killed, and will survive with a permanent injury.",
	"Learn from your mistakes. Don\'t just repeat them and hope you\'ll get lucky this time.",
	"The natural habitat of direwolves is the forest.",
	"You can enable faster AI turns in the options menu.",
	"Trees can be hidden in combat using the \'T\' key.",
	"Objects blocking tiles can be highlighted using the \'B\' key.",
	"Higher renown will unlock more difficult contracts and better pay.",
	"If your plan can fail with bad luck, maybe it isn\'t good enough of a plan.",
	"Do the job. Survive. Get paid.",
	"You need a minimum of 10% bonus across all your brothers for a favoured enemy perk to spawn champions or legendary beasts more frequently",
	"You can change the styles of items in the painting tent, located in your camp. For a price, of course.",
	"Tower shields are cumbersome, but can be used to protect others in addition to the user.",
	"If a character waits their turn, their position in the turn order of the next round is determined with a penalty of 25% to Initiative.",
	"A 95% chance to hit is also a 5% chance to miss.",
	"The \'Lone Wolf\' perk is not affected by nearby dogs or allies that are not part of your company.",
	"The \'Fast Adaptation\' perk reduces variance of randomness.",
	"Glaives, while still spears, do not benefit from thrust master.",
	"With staff block, swordstaffs gain 50% of the bonus.",
	"Just because a brother can\'t deal damage, doesn\'t mean they can\'t be useful.",
	"There are things more sinister in the sands than the old empire...",
	"Consider that enemy encampments on hills are harder to assault, especially if they are fortified.",
	"In the Inventory/Character Screen page, \'A\' key selects previous brother, \'D\' key selects next brother, \'S\' key toggles reserve status.",
	"The \'Perfect Focus\' perk is a good way to deal a lot of damage quickly, for a price.",
	"Nimble only protects hitpoints, not armour.",
	"The \'Ballistics\' skill can greatly increase your chance to hit at far ranges",
	"At 15 points of intensive training will reward that brother with a free perk point and trait",
	"Larger groups on the world map move more slowly - regardless of terrain",
	"Staffs and slings are ideal supporting weapons for those brothers who are not fit for direct combat",
	"The \'Intensive Training\' trait can be increased by spending time training with that brother",
	"Increase your roster size by hiring more retinue members, the more you have the more brothers and sisters you can have!"
];
gt.Const.LoadingScreens <- [
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_02.jpg",
	"ui/screens/loading_screen_03.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_07.jpg",
	"ui/screens/loading_screen_08.jpg"
];

